//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CascadeDBEntities : DbContext
    {
        public CascadeDBEntities()
            : base("name=CascadeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MSI_ComplaintMain> MSI_ComplaintMain { get; set; }
        public DbSet<RACCOUNT> RACCOUNTs { get; set; }
        public DbSet<MSI_ComplaintIssues> MSI_ComplaintIssues { get; set; }
        public DbSet<MSI_ComplaintReceviedBy> MSI_ComplaintReceviedBy { get; set; }
        public DbSet<MSI_DebtorContactMethods> MSI_DebtorContactMethods { get; set; }
        public DbSet<MSI_DebtorContactTime> MSI_DebtorContactTime { get; set; }
        public DbSet<MSI_FinalActionsteps> MSI_FinalActionsteps { get; set; }
        public DbSet<MSI_DebtorProducts> MSI_DebtorProducts { get; set; }
        public DbSet<MSI_OwnerResponses> MSI_OwnerResponses { get; set; }
        public DbSet<MSI_USStates> MSI_USStates { get; set; }
        public DbSet<RAGENCY> RAGENCies { get; set; }
    }
}
