

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MSI.CCAT.Data.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CCATDBEntities : DbContext
{
    public CCATDBEntities()
        : base("name=CCATDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Tbl_QuestionBank> Tbl_QuestionBank { get; set; }

    public DbSet<Tbl_QuestionModule> Tbl_QuestionModule { get; set; }

    public DbSet<Tbl_QuestionResponse> Tbl_QuestionResponse { get; set; }

    public DbSet<module> modules { get; set; }

    public DbSet<pageMenu> pageMenus { get; set; }

    public DbSet<pageMenuGroup> pageMenuGroups { get; set; }

}

}

