//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_ConsumerGender
    {
        public LU_ConsumerGender()
        {
            this.Tbl_ConsumerDetails = new HashSet<Tbl_ConsumerDetails>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Tbl_ConsumerDetails> Tbl_ConsumerDetails { get; set; }
    }
}
