//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_InvestorDesignation
    {
        public LU_InvestorDesignation()
        {
            this.Tbl_InvestorDetails = new HashSet<Tbl_InvestorDetails>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Tbl_InvestorDetails> Tbl_InvestorDetails { get; set; }
    }
}
