//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSI_ComplaintMain
    {
        public string AgencyId { get; set; }
        public string Account { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string MobilePhone { get; set; }
        public string LastFourSSN { get; set; }
        public Nullable<bool> DebtorIdentityVerifiedYN { get; set; }
        public Nullable<int> ContactMethodId { get; set; }
        public Nullable<int> ContactTimeId { get; set; }
        public string CreditorName { get; set; }
        public Nullable<int> DebtProductId { get; set; }
        public string DebtPurchaseBalance { get; set; }
        public string DebtCurrentBalance { get; set; }
        public Nullable<bool> DisputeDebtYN { get; set; }
        public Nullable<bool> DisputeDebtAmountYN { get; set; }
        public Nullable<bool> DisputeDebtDueDateYN { get; set; }
        public string ComplaintID { get; set; }
        public System.DateTime ComplaintDate { get; set; }
        public Nullable<int> ComplaintReceivedByMethodId { get; set; }
        public int ComplaintIssueId { get; set; }
        public string ComplaintNotes { get; set; }
        public Nullable<bool> ComplaintSubmitedToAgencyYN { get; set; }
        public Nullable<System.DateTime> ComplaintSubmitedToAgencyDate { get; set; }
        public Nullable<bool> MoreInfoReqdFromDebtorYN { get; set; }
        public Nullable<System.DateTime> MoreInfoRequestedDate { get; set; }
        public string MoreInfoRequested { get; set; }
        public Nullable<bool> MoreInfoReceivedFromDebtorYN { get; set; }
        public Nullable<System.DateTime> MoreInfoReceivedDate { get; set; }
        public string MoreInfoReceived { get; set; }
        public Nullable<bool> ComplaintSubmittedToOwnerYN { get; set; }
        public Nullable<System.DateTime> ComplaintSubmittedDate { get; set; }
        public Nullable<int> TimeToSubmitDays { get; set; }
        public Nullable<bool> MoreInfoFromAgencyYN { get; set; }
        public Nullable<System.DateTime> MoreInfoFromAgencyRequestedDate { get; set; }
        public string MoreInfoFromAgencyRequested { get; set; }
        public Nullable<bool> MoreInfoFromAgencyReceivedYN { get; set; }
        public string MoreInfoFromAgencyReceived { get; set; }
        public Nullable<System.DateTime> MoreInfoFromAgencyReceivedDate { get; set; }
        public Nullable<int> OwnerResponseId { get; set; }
        public Nullable<System.DateTime> OwnerResponseDate { get; set; }
        public Nullable<int> OwnerResponseDays { get; set; }
        public Nullable<System.DateTime> AgencyResponseToDebtorDate { get; set; }
        public Nullable<int> TotalResponseTimeDays { get; set; }
        public Nullable<bool> DebtorAgreeYN { get; set; }
        public Nullable<bool> NeedFurtherActionYN { get; set; }
        public Nullable<int> FinalActionStepId { get; set; }
        public Nullable<bool> IsViewedByOwner { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<bool> IsViewedByAgency { get; set; }
        public string ComplaintDocument { get; set; }
        public string DebtOwnerProcessDocument { get; set; }
    }
}
