//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAGENCY
    {
        public RAGENCY()
        {
            this.RACCOUNTs = new HashSet<RACCOUNT>();
        }
    
        public int RecordID { get; set; }
        public string AGENCY_ID { get; set; }
        public Nullable<int> ResponsibilityTypeID { get; set; }
        public string USERNAME { get; set; }
        public Nullable<bool> ACTIVE_YN { get; set; }
        public string GROSS_PAYMENTS { get; set; }
        public string NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE { get; set; }
        public string Fax { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public string CONTACT_DESC { get; set; }
        public string TERRITORIES { get; set; }
        public string TaxID { get; set; }
        public string AGENCY_TYPE { get; set; }
        public string CREATE_BANKRUPT { get; set; }
        public string UPDATE_BANKRUPT { get; set; }
        public string CREATE_LEGAL { get; set; }
        public string UPDATE_LEGAL { get; set; }
        public string PASSWORD { get; set; }
        public string VALIDATE_BAL { get; set; }
        public string UPDATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<bool> OpenDesk { get; set; }
        public decimal Budget { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool Restricted { get; set; }
    
        public virtual ICollection<RACCOUNT> RACCOUNTs { get; set; }
    }
}
