//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PortfolioOfAccounts
    {
        public string AccountNumber { get; set; }
        public Nullable<int> AccountOriginal { get; set; }
        public Nullable<int> PortfolioBatchNumber { get; set; }
        public int PortfolioId { get; set; }
        public Nullable<int> PortfolioNumber { get; set; }
    
        public virtual Tbl_Account Tbl_Account { get; set; }
    }
}
