//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Tbl_Account
    {
        public Tbl_Account()
        {
            this.Tbl_ComplaintMain = new HashSet<Tbl_ComplaintMain>();
        }

        public string AccountNumber { get; set; }
        public string CreditorName { get; set; }
        public string AccountOriginal { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string MobilePhone { get; set; }
        public string LastFourSSN { get; set; }
        public Nullable<decimal> DebtPurchaseBalance { get; set; }
        public Nullable<decimal> DebtCurrentBalance { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<int> LawFirmId { get; set; }
        public Nullable<int> CreditIssuerId { get; set; }

        public virtual Tbl_Agency Tbl_Agency { get; set; }
        public virtual Tbl_CreditIssuer Tbl_CreditIssuer { get; set; }
        public virtual Tbl_LawFirm Tbl_LawFirm { get; set; }
        public virtual Tbl_Owner Tbl_Owner { get; set; }
        public virtual Tbl_States Tbl_States { get; set; }
        internal virtual ICollection<Tbl_ComplaintMain> Tbl_ComplaintMain { get; private set; }
    }
}
