//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PortfolioDetails
    {
        public Tbl_PortfolioDetails()
        {
            this.Tbl_Account = new HashSet<Tbl_Account>();
        }
    
        public Nullable<int> CashPosition { get; set; }
        public string ChainOfTitlePortfolio { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyFax { get; set; }
        public string CompanyName { get; set; }
        public string CompanyZip { get; set; }
        public string Contact_Email { get; set; }
        public string Contact_FirstName { get; set; }
        public string Contact_LastName { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<System.DateTime> DateSellerPaid { get; set; }
        public Nullable<int> InitialRateofReturn { get; set; }
        public Nullable<int> InvestorId { get; set; }
        public Nullable<int> LU_CurrentResponsibilityId { get; set; }
        public Nullable<int> LU_PortfolioBLSDesignationId { get; set; }
        public Nullable<int> LU_PortfolioResaleRestrictionId { get; set; }
        public Nullable<int> LU_ResponsibilityCurrentId { get; set; }
        public Nullable<int> LU_ResponsibilityPreviousId { get; set; }
        public Nullable<int> LU_TransactionTypeId { get; set; }
        public Nullable<int> NumberofPaymentsMade { get; set; }
        public Nullable<int> NumberofPaymentsRemaining { get; set; }
        public Nullable<int> PortfolioBatchNumber { get; set; }
        public Nullable<System.DateTime> PortfolioClosingDate { get; set; }
        public Nullable<int> PortfolioCostBasis { get; set; }
        public Nullable<System.DateTime> PortfolioCutOffDate { get; set; }
        public Nullable<decimal> PortfolioFaceValue { get; set; }
        public int PortfolioId { get; set; }
        public Nullable<decimal> PortfolioNetAmountPaid { get; set; }
        public Nullable<decimal> PortfolioNetAmountRemaining { get; set; }
        public Nullable<int> PortfolioNumber { get; set; }
        public Nullable<decimal> PortfolioPurchasePrice { get; set; }
        public Nullable<System.DateTime> PortfolioSaleDate { get; set; }
        public Nullable<decimal> PortfolioSalesPrice { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> PutbackDeadlineDate { get; set; }
        public Nullable<int> PutbackTermDays { get; set; }
        public Nullable<System.DateTime> RecallDate { get; set; }
        public Nullable<int> ReturnOnCapital { get; set; }
        public Nullable<int> SalesBasis { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> WeightedAverageCouponRate { get; set; }
        public Nullable<int> WeightedAverageMonths { get; set; }
        public Nullable<bool> YN_Recall { get; set; }
        public string column_a { get; set; }
        public string column_b { get; set; }
        public string column_c { get; set; }
        public string column_d { get; set; }
        public string column_e { get; set; }
        public Nullable<int> column_f { get; set; }
        public Nullable<int> column_g { get; set; }
        public Nullable<int> column_h { get; set; }
        public Nullable<int> column_i { get; set; }
        public Nullable<int> column_j { get; set; }
        public Nullable<System.DateTime> column_k { get; set; }
        public Nullable<System.DateTime> column_l { get; set; }
        public Nullable<System.DateTime> column_m { get; set; }
        public Nullable<System.DateTime> column_n { get; set; }
        public Nullable<System.DateTime> column_o { get; set; }
        public Nullable<bool> column_p { get; set; }
        public Nullable<bool> column_q { get; set; }
        public Nullable<bool> column_r { get; set; }
        public Nullable<bool> column_s { get; set; }
        public Nullable<bool> column_t { get; set; }
    
        public virtual LU_CurrentResponsibility LU_CurrentResponsibility { get; set; }
        public virtual LU_PortfolioBLSDesignation LU_PortfolioBLSDesignation { get; set; }
        public virtual LU_PortfolioResaleRestriction LU_PortfolioResaleRestriction { get; set; }
        public virtual LU_ResponsibilityCurrent LU_ResponsibilityCurrent { get; set; }
        public virtual LU_ResponsibilityPrevious LU_ResponsibilityPrevious { get; set; }
        public virtual LU_TransactionType LU_TransactionType { get; set; }
        public virtual ICollection<Tbl_Account> Tbl_Account { get; set; }
        public virtual Tbl_InvestorDetails Tbl_InvestorDetails { get; set; }
        public virtual Tbl_States Tbl_States { get; set; }
    }
}
