//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OwnerResponses
    {
        public Tbl_OwnerResponses()
        {
            this.Tbl_ComplaintMain = new HashSet<Tbl_ComplaintMain>();
        }
    
        public int OwnerResponseId { get; set; }
        public string Response { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ICollection<Tbl_ComplaintMain> Tbl_ComplaintMain { get; set; }
    }
}
