//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MediaDetails
    {
        public string AccountNumber { get; set; }
        public Nullable<int> AccountOriginal { get; set; }
        public string CompanySubmittedTo { get; set; }
        public Nullable<System.DateTime> DateMediaConfirmed { get; set; }
        public Nullable<System.DateTime> DateMediaForwarded { get; set; }
        public Nullable<System.DateTime> DateMediaOrdered { get; set; }
        public Nullable<System.DateTime> DateMediaReceived { get; set; }
        public Nullable<System.DateTime> DateMediaSubmitted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> LU_MediaTypeId { get; set; }
        public Nullable<bool> MediaAvailable { get; set; }
        public int MediaId { get; set; }
        public Nullable<decimal> OwnerMediaFee { get; set; }
        public Nullable<decimal> SellerMediaFee { get; set; }
        public string column_a { get; set; }
        public string column_b { get; set; }
        public string column_c { get; set; }
        public string column_d { get; set; }
        public string column_e { get; set; }
        public Nullable<int> column_f { get; set; }
        public Nullable<int> column_g { get; set; }
        public Nullable<int> column_h { get; set; }
        public Nullable<int> column_i { get; set; }
        public Nullable<int> column_j { get; set; }
        public Nullable<System.DateTime> column_k { get; set; }
        public Nullable<System.DateTime> column_l { get; set; }
        public Nullable<System.DateTime> column_m { get; set; }
        public Nullable<System.DateTime> column_n { get; set; }
        public Nullable<System.DateTime> column_o { get; set; }
        public Nullable<bool> column_p { get; set; }
        public Nullable<bool> column_q { get; set; }
        public Nullable<bool> column_r { get; set; }
        public Nullable<bool> column_s { get; set; }
        public Nullable<bool> column_t { get; set; }
    
        public virtual LU_MediaType LU_MediaType { get; set; }
        public virtual Tbl_Account Tbl_Account { get; set; }
    }
}
