//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_QuestionBank
    {
        public Tbl_QuestionBank()
        {
            this.Tbl_QuestionResponse = new HashSet<Tbl_QuestionResponse>();
        }
    
        public int questionId { get; set; }
        public string questionSrNo { get; set; }
        public string questionText { get; set; }
        public Nullable<int> moduleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> displayOrder { get; set; }
    
        public virtual Tbl_QuestionModule Tbl_QuestionModule { get; set; }
        public virtual ICollection<Tbl_QuestionResponse> Tbl_QuestionResponse { get; set; }
    }
}
