//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ConsumerDetails
    {
        public Tbl_ConsumerDetails()
        {
            this.Tbl_Account = new HashSet<Tbl_Account>();
        }
    
        public string Address { get; set; }
        public string City { get; set; }
        public int ConsumerId { get; set; }
        public string County { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Email { get; set; }
        public string Employer { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public string HomePhone { get; set; }
        public Nullable<int> Last4SSN { get; set; }
        public string LastName { get; set; }
        public Nullable<int> LU_ConsumerGenderId { get; set; }
        public string MiddleName { get; set; }
        public string MobilePhone { get; set; }
        public string OldAddress { get; set; }
        public string OldCellPhone { get; set; }
        public string OldCity { get; set; }
        public string OldHomePhone { get; set; }
        public Nullable<int> OldStateId { get; set; }
        public string OldZip { get; set; }
        public string SpouseFirstName { get; set; }
        public string SpouseLastName { get; set; }
        public Nullable<int> StateId { get; set; }
        public string WorkPhone { get; set; }
        public string Zip { get; set; }
        public string column_a { get; set; }
        public string column_b { get; set; }
        public string column_c { get; set; }
        public string column_d { get; set; }
        public string column_e { get; set; }
        public Nullable<int> column_f { get; set; }
        public Nullable<int> column_g { get; set; }
        public Nullable<int> column_h { get; set; }
        public Nullable<int> column_i { get; set; }
        public Nullable<int> column_j { get; set; }
        public Nullable<System.DateTime> column_k { get; set; }
        public Nullable<System.DateTime> column_l { get; set; }
        public Nullable<System.DateTime> column_m { get; set; }
        public Nullable<System.DateTime> column_n { get; set; }
        public Nullable<System.DateTime> column_o { get; set; }
        public Nullable<bool> column_p { get; set; }
        public Nullable<bool> column_q { get; set; }
        public Nullable<bool> column_r { get; set; }
        public Nullable<bool> column_s { get; set; }
        public Nullable<bool> column_t { get; set; }
    
        public virtual LU_ConsumerGender LU_ConsumerGender { get; set; }
        public virtual ICollection<Tbl_Account> Tbl_Account { get; set; }
        public virtual Tbl_States Tbl_States { get; set; }
        public virtual Tbl_States Tbl_States1 { get; set; }
    }
}
