//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Owner
    {
        public Tbl_Owner()
        {
            this.Tbl_Account = new HashSet<Tbl_Account>();
            this.Tbl_Agency = new HashSet<Tbl_Agency>();
            this.Tbl_CreditIssuer = new HashSet<Tbl_CreditIssuer>();
            this.Tbl_LawFirm = new HashSet<Tbl_LawFirm>();
        }
    
        public int OwnerId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Zipcode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string OwnerContact_LastName { get; set; }
        public string OwnerContact_FirstName { get; set; }
        public string OwnerContact_Email { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<Tbl_Account> Tbl_Account { get; set; }
        public virtual ICollection<Tbl_Agency> Tbl_Agency { get; set; }
        public virtual ICollection<Tbl_CreditIssuer> Tbl_CreditIssuer { get; set; }
        public virtual ICollection<Tbl_LawFirm> Tbl_LawFirm { get; set; }
        public virtual Tbl_States Tbl_States { get; set; }
    }
}
