//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_QuestionBank
    {
        public Tbl_QuestionBank()
        {
            this.Tbl_QuestionResponse = new HashSet<Tbl_QuestionResponse>();
        }
    
        public int Id { get; set; }
        public string SrNo { get; set; }
        public string Text { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string ToolTipText { get; set; }
    
        public virtual Tbl_QuestionModule Tbl_QuestionModule { get; set; }
        public virtual ICollection<Tbl_QuestionResponse> Tbl_QuestionResponse { get; set; }
    }
}
