//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cosigner
    {
        public Tbl_Cosigner()
        {
            this.Tbl_Account = new HashSet<Tbl_Account>();
        }
    
        public string Address { get; set; }
        public string City { get; set; }
        public int CosignerId { get; set; }
        public string County { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public string Last4SSN { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Zip { get; set; }
    
        public virtual ICollection<Tbl_Account> Tbl_Account { get; set; }
        public virtual Tbl_States Tbl_States { get; set; }
    }
}
