//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_States
    {
        public Tbl_States()
        {
            this.Tbl_Account = new HashSet<Tbl_Account>();
            this.Tbl_Agency = new HashSet<Tbl_Agency>();
            this.Tbl_CreditIssuer = new HashSet<Tbl_CreditIssuer>();
            this.Tbl_LawFirm = new HashSet<Tbl_LawFirm>();
            this.Tbl_Owner = new HashSet<Tbl_Owner>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<Tbl_Account> Tbl_Account { get; set; }
        public virtual ICollection<Tbl_Agency> Tbl_Agency { get; set; }
        public virtual ICollection<Tbl_CreditIssuer> Tbl_CreditIssuer { get; set; }
        public virtual ICollection<Tbl_LawFirm> Tbl_LawFirm { get; set; }
        public virtual ICollection<Tbl_Owner> Tbl_Owner { get; set; }
    }
}
