//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Vendor
    {
        public Tbl_Vendor()
        {
            this.Tbl_Account = new HashSet<Tbl_Account>();
        }
    
        public string Address { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
        public string City { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Fax { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
        public Nullable<int> FeePercent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> LU_VendorDesignationId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> RevocationDate { get; set; }
        public Nullable<int> StateId { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string VendorContact_Email { get; set; }
        public string VendorContact_FirstName { get; set; }
        public string VendorContact_LastName { get; set; }
        public int VendorId { get; set; }
        public string Zipcode { get; set; }
        public string column_a { get; set; }
        public string column_b { get; set; }
        public string column_c { get; set; }
        public string column_d { get; set; }
        public string column_e { get; set; }
        public Nullable<int> column_f { get; set; }
        public Nullable<int> column_g { get; set; }
        public Nullable<int> column_h { get; set; }
        public Nullable<int> column_i { get; set; }
        public Nullable<int> column_j { get; set; }
        public Nullable<System.DateTime> column_k { get; set; }
        public Nullable<System.DateTime> column_l { get; set; }
        public Nullable<System.DateTime> column_m { get; set; }
        public Nullable<System.DateTime> column_n { get; set; }
        public Nullable<System.DateTime> column_o { get; set; }
        public Nullable<bool> column_p { get; set; }
        public Nullable<bool> column_q { get; set; }
        public Nullable<bool> column_r { get; set; }
        public Nullable<bool> column_s { get; set; }
        public Nullable<bool> column_t { get; set; }
    
        public virtual LU_VendorDesignation LU_VendorDesignation { get; set; }
        public virtual ICollection<Tbl_Account> Tbl_Account { get; set; }
        public virtual Tbl_States Tbl_States { get; set; }
    }
}
