//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_States
    {
        public Tbl_States()
        {
            this.Tbl_Account = new HashSet<Tbl_Account>();
            this.Tbl_Agency = new HashSet<Tbl_Agency>();
            this.Tbl_CreditIssuer = new HashSet<Tbl_CreditIssuer>();
            this.Tbl_LawFirm = new HashSet<Tbl_LawFirm>();
            this.Tbl_Owner = new HashSet<Tbl_Owner>();
            this.Tbl_ConsumerDetails = new HashSet<Tbl_ConsumerDetails>();
            this.Tbl_ConsumerDetails1 = new HashSet<Tbl_ConsumerDetails>();
            this.Tbl_Cosigner = new HashSet<Tbl_Cosigner>();
            this.Tbl_InvestorDetails = new HashSet<Tbl_InvestorDetails>();
            this.Tbl_PortfolioDetails = new HashSet<Tbl_PortfolioDetails>();
            this.Tbl_Vendor = new HashSet<Tbl_Vendor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<Tbl_Account> Tbl_Account { get; set; }
        public virtual ICollection<Tbl_Agency> Tbl_Agency { get; set; }
        public virtual ICollection<Tbl_CreditIssuer> Tbl_CreditIssuer { get; set; }
        public virtual ICollection<Tbl_LawFirm> Tbl_LawFirm { get; set; }
        public virtual ICollection<Tbl_Owner> Tbl_Owner { get; set; }
        public virtual ICollection<Tbl_ConsumerDetails> Tbl_ConsumerDetails { get; set; }
        public virtual ICollection<Tbl_ConsumerDetails> Tbl_ConsumerDetails1 { get; set; }
        public virtual ICollection<Tbl_Cosigner> Tbl_Cosigner { get; set; }
        public virtual ICollection<Tbl_InvestorDetails> Tbl_InvestorDetails { get; set; }
        public virtual ICollection<Tbl_PortfolioDetails> Tbl_PortfolioDetails { get; set; }
        public virtual ICollection<Tbl_Vendor> Tbl_Vendor { get; set; }
    }
}
