//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_InvestorDetails
    {
        public Tbl_InvestorDetails()
        {
            this.Tbl_PortfolioDetails = new HashSet<Tbl_PortfolioDetails>();
        }
    
        public string Address { get; set; }
        public string City { get; set; }
        public string CompanyName { get; set; }
        public string Contact_FirstName { get; set; }
        public string Contact_LastName { get; set; }
        public string County { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string HomePhone { get; set; }
        public Nullable<int> InvestmentPercent { get; set; }
        public int InvestorId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> LU_InvestorDesignationId { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<int> ROIActual { get; set; }
        public Nullable<int> ROIDesired { get; set; }
        public Nullable<int> StateId { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string WorkPhone { get; set; }
        public string Zip { get; set; }
    
        public virtual LU_InvestorDesignation LU_InvestorDesignation { get; set; }
        public virtual Tbl_States Tbl_States { get; set; }
        public virtual ICollection<Tbl_PortfolioDetails> Tbl_PortfolioDetails { get; set; }
    }
}
