//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSI.CCAT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_aspnet_membership
    {
        public string UserName { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public string AgencyName { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string OwnerName { get; set; }
        public Nullable<int> LawFirmId { get; set; }
        public string LawFirmName { get; set; }
        public Nullable<System.Guid> ManagerId { get; set; }
        public string ManagerUsername { get; set; }
        public string RoleName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RoleEntityValue { get; set; }
        public System.Guid UserId { get; set; }
        public string Email { get; set; }
        public bool IsLockedOut { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime LastPasswordChangedDate { get; set; }
        public System.DateTime LastLockoutDate { get; set; }
        public string Comment { get; set; }
    }
}
